### ISSUE TITLE
对话栏的对话数量多了以后会遮挡一部分文字。主程序窗口的毛玻璃效果可能有些问题

### ISSUE THREAD

**Issue by 85spirit** [giri-group/giri-desktop-jira#2]
1.对话的次数多了以后，有一部分对话会被遮挡。
![截屏2023-03-11 15 00 40](https://user-images.githubusercontent.com/40262092/224470787-b2f7de9e-67cf-4382-b8b9-97dd6d5c8aab.png)

2.毛玻璃的效果好像不太对，本应用在最上层的时候是毛玻璃效果，后面背景要是花一点，就看不清文字了。其他应用在最上层的时候，本应用反而不模糊了。。？
![截屏2023-03-11 15 02 52](https://user-images.githubusercontent.com/40262092/224470901-c28dfe17-2c52-49f4-ad4d-7dd9d3528ae5.png)
![截屏2023-03-11 15 12 36](https://user-images.githubusercontent.com/40262092/224470914-a89381f8-1809-49b6-b3dd-01e4fabce742.png)

**Comment by JIACHENG135** [comment]
毛玻璃准备撤掉了。遮挡bug已经修复
